### ISSUE TITLE
Error: Invalid account discriminator

### ISSUE THREAD

**Issue by vitorbferna** [iSyqozz/pump.fun-sniper#2]
For some reason, when I run it now I get this error:

Error: Invalid account discriminator
    at BorshAccountsCoder.decode (/Users/user/Desktop/Sol/SniperBot/PVT1/node_modules/@coral-xyz/anchor/src/coder/borsh/accounts.ts:56:13)
    at AccountClient.fetchNullableAndContext (/Users/user/Desktop/Sol/SniperBot/PVT1/node_modules/@coral-xyz/anchor/src/program/namespace/account.ts:164:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AccountClient.fetch (/Users/user/Desktop/Sol/SniperBot/PVT1/node_modules/@coral-xyz/anchor/src/program/namespace/account.ts:176:22)
    at async main (/Users/user/Desktop/Sol/SniperBot/PVT1/scripts/main.ts:214:31)
an error has occurred

The funny thing is that it is happening with the old version as well, not sure why

**Comment by iSyqozz** [comment]
The platform updated their program.
Deploying the change today
